<a href="https://colab.research.google.com/github/IsabelaNeves1/web_app/blob/main/Analise_culturas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analitycs - Produção de grãos estimada ciclo 2025/2026

In [1]:
import pandas as pd

In [7]:
caminho_drive = '/content/drive/MyDrive/analise_safra_conab_real.csv'

In [8]:
df = pd.read_csv(caminho_drive, sep=';', encoding='utf-8-sig')

In [9]:
print("--- Tabela Geral da Safra 2025/2026 ---")
display(df)

--- Tabela Geral da Safra 2025/2026 ---

,Cultura,Produção Estimada (Milhões t),Variação vs Safra Passada (%),Status/Destaque
0,Soja,180.60,5.3,Aumento de área e clima favorável
1,Milho (Total),141.70,0.4,MT estável; quebras pontuais em GO/MG/PI
2,Arroz,11.10,-13.1,Queda devido a menor área destinada
3,Trigo,6.00,-23.5,Redução de área e menor produtividade esperada
4,Algodão (Pluma),4.06,2.8,Ganho de 2.8% em produtividade compensa menor ...
5,Feijão,3.00,-1.4,"Redução leve, mas garante abastecimento interno"

In [10]:
# Somando a produção de todas as culturas da tabela
total_producao = df['Produção Estimada (Milhões t)'].sum()

# Calculando a porcentagem de representatividade de cada uma
df['Participação (%)'] = (df['Produção Estimada (Milhões t)'] / total_producao) * 100

display(df[['Cultura', 'Produção Estimada (Milhões t)', 'Participação (%)']])

           Cultura  Produção Estimada (Milhões t)  Participação (%)
0             Soja                         180.60         52.127230
1    Milho (Total)                         141.70         40.899382
2            Arroz                          11.10          3.203833
3            Trigo                           6.00          1.731802
4  Algodão (Pluma)                           4.06          1.171852
5           Feijão                           3.00          0.865901

In [11]:
# Culturas com maior crescimento
vencedores = df.sort_values(by='Variação vs Safra Passada (%)', ascending=False)
print("--- Destaques Positivos e Negativos ---")
display(vencedores[['Cultura', 'Variação vs Safra Passada (%)']])

--- Destaques Positivos e Negativos ---

           Cultura  Variação vs Safra Passada (%)
0             Soja                            5.3
4  Algodão (Pluma)                            2.8
1    Milho (Total)                            0.4
5           Feijão                           -1.4
2            Arroz                          -13.1
3            Trigo                          -23.5